### codepy local endpoint

POST https://localhost:8787 HTTP/1.1
content-type: application/json

{
    "prompt": "Write a Python function that takes a list of integers and returns the sum of all the integers in the list"
}

### codepy production endpoint
POST https://codepy.boardflare.workers.dev HTTP/1.1
content-type: application/json

{
    "genText": {
        "model": "codestral-2405",
        "messages": [
            {
                "role": "user",
                "content": "Write a Python function that takes a list of integers and returns the sum of all the integers in the list"
            }
        ],
        "max_tokens": 1000,
        "temperature": 0.1
    }
}