### codepy local endpoint

POST https://localhost:8787 HTTP/1.1
content-type: application/json

{
    "description": "Finds the dot product of two column vectors arg1 and arg2",
    "arg1": [[1], [2], [3]]
}

### codepy production endpoint
POST https://codepy.boardflare.workers.dev HTTP/1.1
content-type: application/json

{
    "description": "Write a Python function that takes a list of integers and returns the sum of all the integers in the list",
    "arg1": [1, 2, 3, 4, 5]
}